package Advanced_DSA_1.Day_18_Bit_Manipulation.ClassVideo;
/*
Q-5: every element occurs twice except two element,
identify those two elements(isolate the two numbers) .
 */
public class Problem_5 {
// process :
    /*
    step-1: do the XOR for all the element for we will get final value which
    is combination of both unique value
    step-2: now we need to identify those two unique value throw which this final value if generated by binary process
    for that we need to identify the position of ith set bit in allXOR
     */

public static void FindUniqueTwoElement(int[] a ,int n){
    int position = 0;
    int finalValueOfXORAll = doXORForAll(a, n);
    // step-2: now need to identify the position of 1-th set bit in allXOR for 32-bit
    for(int i = 0; i<32; i++){
        if(CheckSetBit(finalValueOfXORAll, i)){
            position = i;
            break;
        }
    }

    // step-3: separate entire array into two
    // group g1(position bit is set) g2(position bit is unset)
    int first = 0, second = 0;
    for(int i = 0; i<n; i++){
        if(CheckSetBit(a[i],position)){
            first = first ^ a[i];
        }else{
            second = second ^ a[i];
        }
    }
    System.out.println("first value is : "+first);
    System.out.println("Second value is: "+second);

}
    public static void main(String[] args){
        int[] a = {4,5,5, 6, 6,1,2,2};
        FindUniqueTwoElement(a, a.length);
    }
    public static int doXORForAll(int[]a, int n){
        int ans = 0;
        for(int i = 0; i<n; i++){
            ans = ans ^ a[i];
        }
        return ans;
    }

    public static boolean CheckSetBit(int a , int index){

        if((a & (1<<index)) == 0){
            return false;
        }else{
            return true;
        }
    }
}
